### ISSUE TITLE
Setup app theme & base layout

### ISSUE THREAD

**Issue by addianto** [addianto/unofficial-enterkomputer#3]
Use Material Design components and redesign the main screen to use Bottom Navigation bar.

## Tasks

- [x] Add Material Design dependency into `build.gradle`
- [x] Prepare custom color scheme in `colors.xml`
- [x] Prepare standard margins size in `dimens.xml`
- [x] Prepare custom theme in `styles.xml`
- [x] Add Bottom Navigation bar into the main screen

**Comment by addianto** [comment]
Done in #6.
