### ISSUE TITLE
Create category list

### ISSUE THREAD

**Issue by addianto** [addianto/unofficial-enterkomputer#4]
Create a screen that displays a list of category. Each category is clickable and will show the product list of that particular category.

## Tasks

- [x] Create data model class for representing category
  - [x] `Room`-related: `@Entity`, `@Dao` class for the category
- [x] Create repository layer for reading categories
- [x] Create `ViewModel` for category list
- [x] Design the layout for category list

**Comment by addianto** [comment]
Done in #7
