### ISSUE TITLE
Create product list

### ISSUE THREAD

**Issue by addianto** [addianto/unofficial-enterkomputer#5]
Create a screen that displays a list of products from certain category. Each list item displays at least the name and the price of the product.

## Tasks

- [x] Create data model class for representing product
  - [x] `Room`-related: entity and DAO class
  - [x] Prepare migration script to update the database that previously only contain category records
- [x] Create remote (network) data source for loading the products from EnterKomputer's API
- [x] Create repository layer for syncing products data from API with local cache stored in the database
- [x] Create `ViewModel` for product list
- [x] Design the layout for product list

**Comment by addianto** [comment]
Only implement remote data fetching for now.

**Comment by addianto** [comment]
Done in #8
